" .vimrc
" vim configuration file
" IKARASHI Yoshinori <yoosee@init.org>
"

",v brings up my .vimrc
"",V reloads it -- making all changes active (have to save first)

map ,v :sp $VIMRC_
map <silent> ,V :source $VIMRC:filetype detect:exe ":echo 'vimrc reloaded'"

set nocompatible
"set mapleader = ","
imap jj <Esc>

filetype on
filetype indent on
filetype plugin on

set shiftwidth=2
set tabstop=2
set incsearch
set wildmenu wildmode=list:full
set hlsearch
set number
set nobackup
"if &t_Co > 1
"   syntax enable
"endif
set wildignore=*/tmp*/,*.so,*.zip,*pyc,*.jpg,*.o

" Colors **********************
set t_Co=256 " 256 colors
set background=dark
syntax on " syntax highlighting
colorscheme ir_black
set nohlsearch
set cursorline

" Status Line *************************************************************
set showcmd
set ruler " Show ruler
set laststatus=2
set statusline=%F%r%h%=
"set ch=2 " Make command line two lines high
"match LongLineWarning '\%120v.*' " Error format when a line is longer than 120
 
 
" Line Wrapping ***********************************************************
set nowrap
set linebreak " Wrap at word

autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif


"set termencoding=euc-jp
set termencoding=utf-8
set encoding=japan                             
set fileencoding=utf-8
set fileencodings=utf-8,iso-2022-jp,cp932,japan
set enc=utf-8

set fo=M

let loaded_matchparen = 1

if has("autocmd")
   autocmd FileType changelog
   \ map ,d ggi<CR><CR><ESC>kki<C-R>=strftime("%Y-%m-%d")<CR>
   \ IKARASHI Yoshinori <yoosee@init.org><ESC>o<CR><TAB>*
   \ | map ,n ggo<CR><TAB>*
endif

au FileType ruby  :set nowrap tabstop=2 tw=0 sw=2 expandtab
au FileType eruby :set nowrap tabstop=2 tw=0 sw=2 expandtab
" normal ruby & eRuby
au BufNewFile *.rhtml set ft=eruby fenc=euc-jp
au BufNewFile *.rb    set ft=ruby  fenc=euc-jp
" rails
au BufNewFile,BufRead app/*/*.rhtml	set ft=mason fenc=utf-8
au BufNewFile,BufRead app/**/*.rb	set ft=ruby  fenc=utf-8


