# 
# zshrc
#
# Author : ikarashi yoshinori <yoosee@gmail.com>
# Created: "2001-06-04 00:24:42 yoshi"
# 

#cdpath=(.. ~ ~/work)
path=($path /usr/sbin /sbin ~/local/bin ~/.rvm/bin)
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fpath=(~/.zsh/fpath ~/.zsh/fpath/zsh-completions/src $fpath)

case ${UID} in
0)
  PROMPT=$'%B%{\e[35m%}(%W %T) : [%{\e[32m%}%~%{\e[35m%}]\n%{\e[31m%}%B%n@%m(%h)>%{\e[0m%}%b '
	;;
*)
	PROMPT=$'%B%{\e[30m%}(%W %T) : [%{\e[32m%}%~%{\e[30m%}] $(prompt_stat_char)\n%{\e[0m%}%B%n@%m(%h)>%{\e[0m%}%b '
	;;
esac

setenv() { export $1=$2 }

WATCHFMT='%n %a %l from %m at %t.'

stty -ixon

# zsh options

unsetopt correct_all
setopt correct
CORRECT_IGNORE_FILE='.*'
setopt	notify globdots pushdtohome cdablevars autolist
#setopt	listtype 
setopt	nohup
setopt	autocd recexact longlistjobs
setopt	autoresume histignoredups pushdsilent noclobber
setopt	autopushd pushdminus extendedglob rcquotes mailwarning
setopt  list_packed
unsetopt bgnice autoparamslash allexport

# Key bindings
bindkey -e               # emacs key bindings
#bindkey ' ' magic-space  # also do history expansino on space
#bindkey ' ' self-insert
bindkey '^J' self-insert
bindkey '^r' history-incremental-pattern-search-backward
bindkey '^s' history-incremental-pattern-search-forward

# url-quote-magic 
autoload -U url-quote-magic
zle -N self-insert url-quote-magic

# history
HISTFILE=$HOME/.zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
setopt extended_history
setopt share_history
setopt hist_ignore_all_dups 
setopt hist_find_no_dups
setopt hist_reduce_blanks 
setopt hist_ignore_space
setopt hist_no_store
function history-all { history -E 1 } 

# keychain
case ${UID} in
1000)
  if [[ $USE_KEYCHAIN = 1 ]] ; then
    keychain id_rsa
    source $HOME/.keychain/`hostname`-sh
  fi
	;;
esac

chpwd() {
	[[ -t 1 ]] || return
	case $TERM in 
	*xterm*|rxvt|(dt|k|E|gnome-)term) print -Pn "\e]2;%m: %~\a"
	;;
	esac
}


#
# include external files
#
source ~/.zshcomp       # compretion setting
source ~/.zshenv        # environment values
source ~/.zshalias      # aliases
source ~/.zshfunc	# functions

if [ -f ~/local/config/host.d/zshrc-${HOST} ]; then
  source ~/local/config/host.d/zshrc-${HOST}
else
  source ~/local/config/host.d/zshrc-general
fi

